/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gva.asa.forms.managers.util;

import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;

/**
 *
 * @author farnauvi
 */
public class EditorFrame extends javax.swing.JFrame implements ServerListener {
    
    ThreadServer hiloExec = null;

    /**
     * Creates new form EditorFrame
     */
    public EditorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EntornoPanel = new javax.swing.JPanel();
        EntornosComboBox = new javax.swing.JComboBox<>();
        ConsultaAmbitos = new javax.swing.JButton();
        EntornosLabel = new javax.swing.JLabel();
        UsernameTF = new javax.swing.JTextField();
        UserLabel = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        PasswordF = new javax.swing.JPasswordField();
        ServersPanel = new javax.swing.JPanel();
        OutputPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        AmbitoPanel = new javax.swing.JPanel();
        filePanel = new javax.swing.JPanel();
        newAmbitoPanel = new javax.swing.JPanel();
        newAmbitoButton = new javax.swing.JButton();
        newAmbitoTF = new javax.swing.JTextField();
        editButtonPanel = new javax.swing.JPanel();
        editFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EntornoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Entorno"));

        EntornosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desarrollo_Forms_11", "Pre_Forms_11_Interno", "Pre_Forms_11_Externo", "Pro_Forms_11_Interno", "Pro_Forms_11_Externo" }));
        EntornosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntornosComboBoxActionPerformed(evt);
            }
        });

        ConsultaAmbitos.setText("Consultar");
        ConsultaAmbitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaAmbitosActionPerformed(evt);
            }
        });

        EntornosLabel.setText("Seleccione entorno:");

        UsernameTF.setToolTipText("");

        UserLabel.setText("Usuario:");

        PassLabel.setText("Pass:");

        PasswordF.setToolTipText("");

        ServersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Servidores"));
        ServersPanel.setLayout(new javax.swing.BoxLayout(ServersPanel, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout EntornoPanelLayout = new javax.swing.GroupLayout(EntornoPanel);
        EntornoPanel.setLayout(EntornoPanelLayout);
        EntornoPanelLayout.setHorizontalGroup(
            EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntornoPanelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ConsultaAmbitos)
                    .addGroup(EntornoPanelLayout.createSequentialGroup()
                        .addGroup(EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PassLabel)
                            .addComponent(EntornosLabel)
                            .addComponent(UserLabel))
                        .addGap(23, 23, 23)
                        .addGroup(EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(UsernameTF)
                            .addComponent(EntornosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordF))))
                .addGap(19, 19, 19))
            .addGroup(EntornoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ServersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        EntornoPanelLayout.setVerticalGroup(
            EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntornoPanelLayout.createSequentialGroup()
                .addGroup(EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntornosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntornosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassLabel)
                    .addComponent(PasswordF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConsultaAmbitos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        OutputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro - Log"));

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane.setViewportView(logTextArea);

        javax.swing.GroupLayout OutputPanelLayout = new javax.swing.GroupLayout(OutputPanel);
        OutputPanel.setLayout(OutputPanelLayout);
        OutputPanelLayout.setHorizontalGroup(
            OutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane)
                .addContainerGap())
        );
        OutputPanelLayout.setVerticalGroup(
            OutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        AmbitoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ámbitos"));
        AmbitoPanel.setToolTipText("Selección");

        filePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        filePanel.setLayout(new javax.swing.BoxLayout(filePanel, javax.swing.BoxLayout.LINE_AXIS));

        newAmbitoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        newAmbitoPanel.setLayout(new javax.swing.BoxLayout(newAmbitoPanel, javax.swing.BoxLayout.X_AXIS));

        newAmbitoButton.setText("Crear nuevo ámbito:");
        newAmbitoButton.setEnabled(false);
        newAmbitoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAmbitoButtonActionPerformed(evt);
            }
        });
        newAmbitoPanel.add(newAmbitoButton);

        newAmbitoTF.setToolTipText("");
        newAmbitoPanel.add(newAmbitoTF);

        editFileButton.setText("Editar ámbito/fichero");
        editFileButton.setEnabled(false);
        editFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editButtonPanelLayout = new javax.swing.GroupLayout(editButtonPanel);
        editButtonPanel.setLayout(editButtonPanelLayout);
        editButtonPanelLayout.setHorizontalGroup(
            editButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editButtonPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(editFileButton)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        editButtonPanelLayout.setVerticalGroup(
            editButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editFileButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout AmbitoPanelLayout = new javax.swing.GroupLayout(AmbitoPanel);
        AmbitoPanel.setLayout(AmbitoPanelLayout);
        AmbitoPanelLayout.setHorizontalGroup(
            AmbitoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AmbitoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AmbitoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newAmbitoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        AmbitoPanelLayout.setVerticalGroup(
            AmbitoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AmbitoPanelLayout.createSequentialGroup()
                .addComponent(filePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newAmbitoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OutputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EntornoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(AmbitoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EntornoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AmbitoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OutputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntornosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntornosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntornosComboBoxActionPerformed

    private void ConsultaAmbitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaAmbitosActionPerformed
            hiloExec = new ThreadServer();
            hiloExec.addServerListener(this);
            ServersPanel.removeAll();
            repaint();
            String entornoSeleccionado = EntornosComboBox.getSelectedItem().toString();
            System.out.println(entornoSeleccionado);
            String separador = Pattern.quote(",");
            String[] servers = java.util.ResourceBundle.getBundle("gva/asa/forms/resources/Bundle").getString(entornoSeleccionado).split(separador);
            ServersPanel.removeAll();
            logTextArea.setText("");
            hiloExec.consultaAmbitos(servers[0],UsernameTF.getText(),PasswordF.getText());
            filePanel.removeAll();
            JPanel jpan = new JPanel();
            jpan.setLayout(new BoxLayout(jpan, BoxLayout.Y_AXIS));
            ButtonGroup buttonFiles = new ButtonGroup();

            // FORMSWEB //

            JRadioButton a = new JRadioButton("formsweb.cfg");
            a.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    String a = evt.getActionCommand();
                    hiloExec.RUTA_FILE = hiloExec.RUTA_FORMSWEB;
                    hiloExec.FILE = "formsweb.cfg";
                }
            });
            buttonFiles.add(a);
            jpan.add(a);
            a.setVisible(true);
            jpan.add(new JSeparator(SwingConstants.HORIZONTAL));

            // TNSNAMES //

            JRadioButton c = new JRadioButton("tnsnames.ora");
            c.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    String c = evt.getActionCommand();
                    hiloExec.RUTA_FILE = hiloExec.RUTA_TNSNAMES;
                    hiloExec.FILE = "tnsnames.ora";
                }
            });
            buttonFiles.add(c);
            jpan.add(c);
            c.setVisible(true);
            jpan.add(new JSeparator(SwingConstants.HORIZONTAL));

            // AMBITOS //
            int i=0;
            for (String file: hiloExec.FilesEncontrados ) {
                i++;
                JRadioButton b = new JRadioButton(file);
                b.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        String a = evt.getActionCommand();
                        hiloExec.RUTA_FILE = hiloExec.RUTA_AMBITOS;
                        hiloExec.FILE = a;
                    }
                });
                buttonFiles.add(b);
                jpan.add(b);
                b.setVisible(true);
            }

            jpan.add(new JSeparator(SwingConstants.HORIZONTAL));

            JLabel Servidores = new JLabel("-  Servidores  del entorno  -");
            ServersPanel.add(Servidores);
            i=0;
            for (String server: servers) {
                JLabel lserver = new JLabel("     "+server);
                if (i==0) lserver.setForeground(Color.BLUE);
                ServersPanel.add(lserver);
                i++;
            }
            filePanel.add(jpan);
            pack();
            editFileButton.setEnabled(true);
        
    }//GEN-LAST:event_ConsultaAmbitosActionPerformed

    private void newAmbitoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAmbitoButtonActionPerformed
        
    }//GEN-LAST:event_newAmbitoButtonActionPerformed

    private void editFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFileButtonActionPerformed
        
    }//GEN-LAST:event_editFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AmbitoPanel;
    private javax.swing.JButton ConsultaAmbitos;
    private javax.swing.JPanel EntornoPanel;
    private javax.swing.JComboBox<String> EntornosComboBox;
    private javax.swing.JLabel EntornosLabel;
    private javax.swing.JPanel OutputPanel;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JPasswordField PasswordF;
    private javax.swing.JPanel ServersPanel;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JPanel editButtonPanel;
    private javax.swing.JButton editFileButton;
    private javax.swing.JPanel filePanel;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JButton newAmbitoButton;
    private javax.swing.JPanel newAmbitoPanel;
    private javax.swing.JTextField newAmbitoTF;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cambioEstadoProducido(String text) {
        if ((!(text.equals(hiloExec.PASSWORD+hiloExec.ENTER_KEY)))&&(!(text.startsWith("bash:")))&&(!(text.contains("sudo")))) {
            logTextArea.setText(text);
            System.out.println(text);
        }
    }
}
