/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gva.asa.forms.managers;

import gva.asa.forms.managers.util.ServerListener;
import gva.asa.forms.managers.util.ThreadServer;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.regex.Pattern;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author farnauvi
 */
public class EditorFrame extends javax.swing.JFrame implements ServerListener {
    
    ThreadServer hiloExec = null;

    /**
     * Creates new form EditorFrame
     */
    public EditorFrame() {
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        this.setIconImage(kit.getImage(getClass().getResource(java.util.ResourceBundle.getBundle("gva/asa/forms/resources/Bundle").getString("icoGVA"))));
        startModule();
    }

    public void startModule() {       
            DefaultCaret caret = (DefaultCaret)logTextArea.getCaret();
            caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditorPanel = new javax.swing.JPanel();
        guardar = new javax.swing.JButton();
        DistribuirButton = new javax.swing.JButton();
        editorScrollPanel = new javax.swing.JScrollPane();
        EditorTextArea = new javax.swing.JTextArea();
        EntornoPanel = new javax.swing.JPanel();
        EntornosComboBox = new javax.swing.JComboBox<>();
        ConsultaAmbitos = new javax.swing.JButton();
        EntornosLabel = new javax.swing.JLabel();
        UsernameTF = new javax.swing.JTextField();
        UserLabel = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        PasswordF = new javax.swing.JPasswordField();
        ServersPanel = new javax.swing.JPanel();
        OutputPanel = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        AmbitoPanel = new javax.swing.JPanel();
        filePanel = new javax.swing.JPanel();
        newAmbitoPanel = new javax.swing.JPanel();
        newAmbitoButton = new javax.swing.JButton();
        newAmbitoTF = new javax.swing.JTextField();
        editButtonPanel = new javax.swing.JPanel();
        editFileButton = new javax.swing.JButton();
        state = new javax.swing.JLabel();
        DistribucionPanel = new javax.swing.JPanel();
        pre_f11_int_rb = new javax.swing.JRadioButton();
        pro_f11_int_rb = new javax.swing.JRadioButton();
        pro_f11_ext_rb = new javax.swing.JRadioButton();
        desa_f11_rb = new javax.swing.JRadioButton();
        pre_f11_ext_rb = new javax.swing.JRadioButton();
        versionPanel = new javax.swing.JPanel();
        versionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forms Manager");

        EditorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Editor"));

        guardar.setText("Guardar");
        guardar.setEnabled(false);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        DistribuirButton.setText("Distribuir");
        DistribuirButton.setToolTipText("");
        DistribuirButton.setEnabled(false);
        DistribuirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistribuirButtonActionPerformed(evt);
            }
        });

        EditorTextArea.setColumns(20);
        EditorTextArea.setRows(5);
        editorScrollPanel.setViewportView(EditorTextArea);

        javax.swing.GroupLayout EditorPanelLayout = new javax.swing.GroupLayout(EditorPanel);
        EditorPanel.setLayout(EditorPanelLayout);
        EditorPanelLayout.setHorizontalGroup(
            EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editorScrollPanel)
                    .addGroup(EditorPanelLayout.createSequentialGroup()
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DistribuirButton)))
                .addContainerGap())
        );
        EditorPanelLayout.setVerticalGroup(
            EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editorScrollPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DistribuirButton)
                    .addComponent(guardar))
                .addContainerGap())
        );

        EntornoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Entorno"));

        EntornosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desarrollo_Forms_11", "Pre_Forms_11_Interno", "Pre_Forms_11_Externo", "Pro_Forms_11_Interno", "Pro_Forms_11_Externo" }));
        EntornosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntornosComboBoxActionPerformed(evt);
            }
        });

        ConsultaAmbitos.setText("Consultar");
        ConsultaAmbitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaAmbitosActionPerformed(evt);
            }
        });

        EntornosLabel.setText("Seleccione entorno:");

        UsernameTF.setText("D20156833R");
        UsernameTF.setToolTipText("");

        UserLabel.setText("Usuario:");

        PassLabel.setText("Pass:");

        PasswordF.setText("Nte%0p1a!");
        PasswordF.setToolTipText("");

        ServersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Servidores"));
        ServersPanel.setLayout(new javax.swing.BoxLayout(ServersPanel, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout EntornoPanelLayout = new javax.swing.GroupLayout(EntornoPanel);
        EntornoPanel.setLayout(EntornoPanelLayout);
        EntornoPanelLayout.setHorizontalGroup(
            EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntornoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ConsultaAmbitos)
                    .addGroup(EntornoPanelLayout.createSequentialGroup()
                        .addGroup(EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PassLabel)
                            .addComponent(EntornosLabel)
                            .addComponent(UserLabel))
                        .addGap(23, 23, 23)
                        .addGroup(EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(UsernameTF)
                            .addComponent(EntornosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordF))))
                .addGap(19, 19, 19))
            .addGroup(EntornoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ServersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        EntornoPanelLayout.setVerticalGroup(
            EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntornoPanelLayout.createSequentialGroup()
                .addGroup(EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntornosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntornosLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EntornoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassLabel)
                    .addComponent(PasswordF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConsultaAmbitos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ServersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        OutputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro - Log"));

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane.setViewportView(logTextArea);

        javax.swing.GroupLayout OutputPanelLayout = new javax.swing.GroupLayout(OutputPanel);
        OutputPanel.setLayout(OutputPanelLayout);
        OutputPanelLayout.setHorizontalGroup(
            OutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane)
                .addContainerGap())
        );
        OutputPanelLayout.setVerticalGroup(
            OutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        AmbitoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Ámbitos"));
        AmbitoPanel.setToolTipText("Selección");

        filePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        filePanel.setLayout(new javax.swing.BoxLayout(filePanel, javax.swing.BoxLayout.LINE_AXIS));

        newAmbitoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        newAmbitoPanel.setLayout(new javax.swing.BoxLayout(newAmbitoPanel, javax.swing.BoxLayout.X_AXIS));

        newAmbitoButton.setText("Crear nuevo ámbito:");
        newAmbitoButton.setEnabled(false);
        newAmbitoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAmbitoButtonActionPerformed(evt);
            }
        });
        newAmbitoPanel.add(newAmbitoButton);

        newAmbitoTF.setToolTipText("");
        newAmbitoPanel.add(newAmbitoTF);

        editFileButton.setText("Editar ámbito/fichero");
        editFileButton.setEnabled(false);
        editFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFileButtonActionPerformed(evt);
            }
        });

        state.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gva/asa/forms/resources/green_bole.png"))); // NOI18N

        javax.swing.GroupLayout editButtonPanelLayout = new javax.swing.GroupLayout(editButtonPanel);
        editButtonPanel.setLayout(editButtonPanelLayout);
        editButtonPanelLayout.setHorizontalGroup(
            editButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editFileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(state)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        editButtonPanelLayout.setVerticalGroup(
            editButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editFileButton)
                    .addComponent(state))
                .addContainerGap())
        );

        javax.swing.GroupLayout AmbitoPanelLayout = new javax.swing.GroupLayout(AmbitoPanel);
        AmbitoPanel.setLayout(AmbitoPanelLayout);
        AmbitoPanelLayout.setHorizontalGroup(
            AmbitoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AmbitoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AmbitoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AmbitoPanelLayout.createSequentialGroup()
                        .addComponent(filePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(newAmbitoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        AmbitoPanelLayout.setVerticalGroup(
            AmbitoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AmbitoPanelLayout.createSequentialGroup()
                .addComponent(filePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newAmbitoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DistribucionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel de Distribución"));

        pre_f11_int_rb.setText("Pre_Forms_11_Interno");
        pre_f11_int_rb.setToolTipText("");

        pro_f11_int_rb.setText("Pro_Forms_11_Interno");
        pro_f11_int_rb.setToolTipText("");

        pro_f11_ext_rb.setText("Pro_Forms_11_Externo");

        desa_f11_rb.setText("Desarrollo_Forms_11");

        pre_f11_ext_rb.setText("Pre_Forms_11_Externo");
        pre_f11_ext_rb.setToolTipText("");

        javax.swing.GroupLayout DistribucionPanelLayout = new javax.swing.GroupLayout(DistribucionPanel);
        DistribucionPanel.setLayout(DistribucionPanelLayout);
        DistribucionPanelLayout.setHorizontalGroup(
            DistribucionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DistribucionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DistribucionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desa_f11_rb)
                    .addComponent(pre_f11_int_rb)
                    .addComponent(pre_f11_ext_rb)
                    .addComponent(pro_f11_int_rb)
                    .addComponent(pro_f11_ext_rb))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        DistribucionPanelLayout.setVerticalGroup(
            DistribucionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DistribucionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desa_f11_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pre_f11_int_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pre_f11_ext_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pro_f11_int_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pro_f11_ext_rb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        versionLabel.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        versionLabel.setText("Versión 1.03");
        versionLabel.setToolTipText("");

        javax.swing.GroupLayout versionPanelLayout = new javax.swing.GroupLayout(versionPanel);
        versionPanel.setLayout(versionPanelLayout);
        versionPanelLayout.setHorizontalGroup(
            versionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, versionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(versionLabel)
                .addContainerGap())
        );
        versionPanelLayout.setVerticalGroup(
            versionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, versionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(versionLabel))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EntornoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AmbitoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(OutputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(versionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EditorPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DistribucionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EditorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DistribucionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntornoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AmbitoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OutputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntornosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntornosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntornosComboBoxActionPerformed

    private void distribuyeCambios() {
        if (pre_f11_int_rb.isSelected()) {
            String[] servers = java.util.ResourceBundle.getBundle("gva/asa/forms/resources/Bundle").getString(pre_f11_int_rb.getText()).split(",");
            for (String server: servers) {
              distribuyeFile(server);  
              System.out.println(server);
            }
        }
        if (pre_f11_ext_rb.isSelected()) {
            String[] servers = java.util.ResourceBundle.getBundle("gva/asa/forms/resources/Bundle").getString(pre_f11_ext_rb.getText()).split(",");
            for (String server: servers) {
              distribuyeFile(server);  
              System.out.println(server);
            }
        }
        if (desa_f11_rb.isSelected()) {
            String[] servers = java.util.ResourceBundle.getBundle("gva/asa/forms/resources/Bundle").getString(desa_f11_rb.getText()).split(",");
            for (String server: servers) {
              distribuyeFile(server);  
              System.out.println(server);
            }
        }
        if (pro_f11_int_rb.isSelected()) {
            String[] servers = java.util.ResourceBundle.getBundle("gva/asa/forms/resources/Bundle").getString(pro_f11_int_rb.getText()).split(",");
            for (String server: servers) {
              distribuyeFile(server);  
              System.out.println(server);
            }
        }
         if (pro_f11_ext_rb.isSelected()) {
            String[] servers = java.util.ResourceBundle.getBundle("gva/asa/forms/resources/Bundle").getString(pro_f11_ext_rb.getText()).split(",");
            for (String server: servers) {
              distribuyeFile(server);  
              System.out.println(server);
            }
        }
    }
    
    private void distribuyeFile(String server) {
        hiloExec.ERROR=0;
        hiloExec.HOST=server;
        guardar(EditorTextArea.getText());
        if (hiloExec.ERROR==0) {
            cambioEstadoProducido("Server:"+server+" Fichero "+hiloExec.FILE+" guardado OK");
        }
    }
    
    
    private void ConsultaAmbitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaAmbitosActionPerformed
            hiloExec = new ThreadServer();
            hiloExec.addServerListener(this);
            newAmbitoButton.setEnabled(true);
            newAmbitoTF.setText("");
            ServersPanel.removeAll();
            repaint();
            String entornoSeleccionado = EntornosComboBox.getSelectedItem().toString();
            System.out.println(entornoSeleccionado);
            String separador = Pattern.quote(",");
            String[] servers = java.util.ResourceBundle.getBundle("gva/asa/forms/resources/Bundle").getString(entornoSeleccionado).split(separador);
            ServersPanel.removeAll();
            logTextArea.setText("");
            hiloExec.consultaAmbitos(servers[0],UsernameTF.getText(),PasswordF.getText());
            filePanel.removeAll();
            JPanel jpan = new JPanel();
            jpan.setLayout(new BoxLayout(jpan, BoxLayout.Y_AXIS));
            ButtonGroup buttonFiles = new ButtonGroup();

            // FORMSWEB //

            JRadioButton a = new JRadioButton("formsweb.cfg");
            a.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    String a = evt.getActionCommand();
                    hiloExec.RUTA_FILE = hiloExec.RUTA_FORMSWEB;
                    hiloExec.FILE = "formsweb.cfg";
                }
            });
            buttonFiles.add(a);
            jpan.add(a);
            a.setVisible(true);
            jpan.add(new JSeparator(SwingConstants.HORIZONTAL));

            // TNSNAMES //

            JRadioButton c = new JRadioButton("tnsnames.ora");
            c.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    String c = evt.getActionCommand();
                    hiloExec.RUTA_FILE = hiloExec.RUTA_TNSNAMES;
                    hiloExec.FILE = "tnsnames.ora";
                }
            });
            buttonFiles.add(c);
            jpan.add(c);
            c.setVisible(true);
            jpan.add(new JSeparator(SwingConstants.HORIZONTAL));

            // AMBITOS //
            int i=0;
            for (String file: hiloExec.FilesEncontrados ) {
                i++;
                JRadioButton b = new JRadioButton(file);
                b.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        String a = evt.getActionCommand();
                        hiloExec.RUTA_FILE = hiloExec.RUTA_AMBITOS;
                        hiloExec.FILE = a;
                    }
                });
                buttonFiles.add(b);
                jpan.add(b);
                b.setVisible(true);
            }

            jpan.add(new JSeparator(SwingConstants.HORIZONTAL));

            JLabel Servidores = new JLabel("-  Servidores  del entorno  -");
            ServersPanel.add(Servidores);
            i=0;
            for (String server: servers) {
                JLabel lserver = new JLabel("     "+server);
                if (i==0) lserver.setForeground(Color.BLUE);
                ServersPanel.add(lserver);
                i++;
            }
            filePanel.add(jpan);
            pack();
            editFileButton.setEnabled(true);
            finProceso();
        
    }//GEN-LAST:event_ConsultaAmbitosActionPerformed

    private void newAmbitoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAmbitoButtonActionPerformed
        creaAmbito(EditorTextArea.getText());
    }//GEN-LAST:event_newAmbitoButtonActionPerformed

    private void creaAmbito(String text) {
        hiloExec.FILE = newAmbitoTF.getText();
        hiloExec.creaAmbito(text);
        if (hiloExec.ERROR==0) {
            DistribuirButton.setEnabled(true);
        }
        finProceso();
    }
    
    private void editFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFileButtonActionPerformed
        guardar.setEnabled(true);
        EditorTextArea.setText("");
        logTextArea.setText("");
        hiloExec.abreFichero();
        DistribuirButton.setEnabled(false);
        finProceso();
    }//GEN-LAST:event_editFileButtonActionPerformed

    private void DistribuirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistribuirButtonActionPerformed
        
        int response = JOptionPane.showConfirmDialog(this, "Está Seguro de distribuir el fichero "+hiloExec.FILE+" a los entornos seleccionados?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        switch (response) {
            case JOptionPane.YES_OPTION:
                distribuyeCambios();
                break;
            case JOptionPane.CLOSED_OPTION:
                System.out.println("JOptionPane closed");
                break;
            default:
                break;
        }
        
        
    }//GEN-LAST:event_DistribuirButtonActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        guardar(EditorTextArea.getText());
    }//GEN-LAST:event_guardarActionPerformed

     private void guardar(String text) {
        hiloExec.guardar(text);
        if (hiloExec.ERROR==0) {
            DistribuirButton.setEnabled(true);
        }
        finProceso();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AmbitoPanel;
    private javax.swing.JButton ConsultaAmbitos;
    private javax.swing.JPanel DistribucionPanel;
    private javax.swing.JButton DistribuirButton;
    private javax.swing.JPanel EditorPanel;
    private javax.swing.JTextArea EditorTextArea;
    private javax.swing.JPanel EntornoPanel;
    private javax.swing.JComboBox<String> EntornosComboBox;
    private javax.swing.JLabel EntornosLabel;
    private javax.swing.JPanel OutputPanel;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JPasswordField PasswordF;
    private javax.swing.JPanel ServersPanel;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JRadioButton desa_f11_rb;
    private javax.swing.JPanel editButtonPanel;
    private javax.swing.JButton editFileButton;
    private javax.swing.JScrollPane editorScrollPanel;
    private javax.swing.JPanel filePanel;
    private javax.swing.JButton guardar;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JButton newAmbitoButton;
    private javax.swing.JPanel newAmbitoPanel;
    private javax.swing.JTextField newAmbitoTF;
    private javax.swing.JRadioButton pre_f11_ext_rb;
    private javax.swing.JRadioButton pre_f11_int_rb;
    private javax.swing.JRadioButton pro_f11_ext_rb;
    private javax.swing.JRadioButton pro_f11_int_rb;
    private javax.swing.JLabel state;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JPanel versionPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cambioEstadoProducido(String text) {
        if ((!(text.equals(hiloExec.PASSWORD+hiloExec.ENTER_KEY)))&&(!(text.startsWith("bash:")))&&(!(text.contains("sudo")))) {
            logTextArea.append(text+hiloExec.ENTER_KEY);
            logTextArea.update(logTextArea.getGraphics());
            state.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gva/asa/forms/resources/red_bole.png")));
            state.update(state.getGraphics());
        }
    }

    @Override
    public void ficheroEditado(String text) {
        EditorTextArea.append(text);
    }
    
    public void finProceso() {
        state.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gva/asa/forms/resources/green_bole.png")));
        state.update(state.getGraphics());
    }

}
